from flask import Flask

app = Flask(__name__)
from flask import render_template

@app.route('/hello/')
@app.route('/hello/<name>')
def hello(name=None):
    return render_template('hello.html', otto=name)


@app.route('/index/')
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/predict/')
@app.route('/')
def predict():
    amenities = {'24-Hour Check-in',
     '24-hour check-in',
     'Accessible-height bed',
     'Accessible-height toilet',
     'Air Conditioning',
     'Air conditioning',
     'BBQ grill',
     'Baby bath',
     'Baby monitor',
     'Babysitter recommendations',
     'Bathtub',
     'Beach essentials',
     'Bed linens',
     'Breakfast',
     'Buzzer/Wireless Intercom',
     'Buzzer/wireless intercom',
     'Cable TV',
     'Carbon Monoxide Detector',
     'Carbon monoxide detector',
     'Cat(s)',
     'Changing table',
     'Children’s books and toys',
     'Children’s dinnerware',
     'Cleaning before checkout',
     'Coffee maker',
     'Cooking basics',
     'Crib',
     'Disabled parking spot',
     'Dishes and silverware',
     'Dishwasher',
     'Dog(s)',
     'Doorman',
     'Doorman Entry',
     'Dryer',
     'EV charger',
     'Elevator in Building',
     'Elevator in building',
     'Essentials',
     'Ethernet connection',
     'Extra pillows and blankets',
     'Family/Kid Friendly',
     'Family/kid friendly',
     'Fire Extinguisher',
     'Fire extinguisher',
     'Fireplace guards',
     'Firm matress',
     'First Aid Kit',
     'First aid kit',
     'Flat smooth pathway to front door',
     'Free Parking on Premises',
     'Free Parking on Street',
     'Free parking on premises',
     'Free parking on street',
     'Game console',
     'Garden or backyard',
     'Grab-rails for shower and toilet',
     'Gym',
     'Hair Dryer',
     'Hair dryer',
     'Hangers',
     'Heating',
     'High chair',
     'Hot Tub',
     'Hot tub',
     'Hot water',
     'Indoor Fireplace',
     'Indoor fireplace',
     'Internet',
     'Iron',
     'Keypad',
     'Kitchen',
     'Laptop Friendly Workspace',
     'Laptop friendly workspace',
     'Lock on Bedroom Door',
     'Lock on bedroom door',
     'Lockbox',
     'Long term stays allowed',
     'Luggage dropoff allowed',
     'Microwave',
     'Other pet(s)',
     'Outlet covers',
     'Oven',
     'Pack ’n Play/travel crib',
     'Paid Parking Off Premises',
     'Paid parking off premises',
     'Path to entrance lit at night',
     'Patio or balcony',
     'Pets Allowed',
     'Pets allowed',
     'Pets live on this property',
     'Pocket wifi',
     'Pool',
     'Private bathroom',
     'Private entrance',
     'Private living room',
     'Refrigerator',
     'Room-darkening shades',
     'Safety Card',
     'Safety card',
     'Self Check-In',
     'Shampoo',
     'Single level home',
     'Smartlock',
     'Smoke Detector',
     'Smoke detector',
     'Smoking Allowed',
     'Smoking allowed',
     'Stair gates',
     'Step-free access',
     'Stove',
     'Suitable for Events',
     'Suitable for events',
     'TV',
     'Table corner guards',
     'Washer',
     'Washer / Dryer',
     'Wheelchair Accessible',
     'Wheelchair accessible',
     'Wide clearance to bed',
     'Wide clearance to shower and toilet',
     'Wide doorway',
     'Wide hallway clearance',
     'Window guards',
     'Wireless Internet',
     'translation missing: en.hosting_amenity_49',
     'translation missing: en.hosting_amenity_50'}
    amenities = sorted(list({amenity.title() for amenity in amenities if 'translation' not in amenity}))

    cancellation_policy_types = sorted(['moderate', 'flexible', 'strict', 'no_refunds', 'super_strict_30',
       'long_term', 'super_strict_60'])
    bed_types = sorted(['Real Bed', 'Airbed', 'Futon', 'Pull-out Sofa', 'Couch'])
    property_types = sorted(['House', 'Apartment', 'Loft', 'Dorm', 'Condominium',
       'Bed & Breakfast', 'Other', 'Townhouse', 'Guesthouse', 'Boat',
       'Hostel', 'Bungalow', 'Timeshare', 'Boutique hotel', 'Guest suite',
       'Tent', 'In-law', 'Serviced apartment', 'Villa', 'Cabin',
       'Earth House', 'Cave', 'Castle', 'Lighthouse', 'Hut',
       'Vacation home', 'Chalet', 'Camper/RV', 'Treehouse', 'Island',
       'Train', 'Entire Floor'])
    return render_template('predict.html', amenities = amenities, cancellation_policy_types = cancellation_policy_types,
                           bed_types=bed_types, property_types=property_types)
